apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scratch-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scratch-local-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /scratch
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cmsse-nfs-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 10.4.5.4
    path: /export/cms
---