apiVersion: v1
kind: Pod
metadata:
  name: cvmfs-test
spec:
  containers:
    - name: cvmfs-test
      image: gitlab-registry.cern.ch/akalinow/cmssw-docker/el9-cms:latest
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh", "-c", "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
      env:
        - name: LCG_VERSION
          valueFrom:
            configMapKeyRef:
              name: configs
              key: LCG_VERSION
        - name: LCG_ARCH
          valueFrom:
            configMapKeyRef:
              name: configs
              key: LCG_ARCH
      volumeMounts:
        - name: cvmfs
          mountPath: /cvmfs
          # CVMFS automount volumes must be mounted with HostToContainer mount propagation.
          mountPropagation: HostToContainer
  volumes:
    - name: cvmfs
      persistentVolumeClaim:
        claimName: cvmfs-pvc


