---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvmfs
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cvmfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cvmfs
  hostPath:
    path: /cvmfs
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-pvc
spec:
  storageClassName: cvmfs
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
---